In [1]:
import numpy as np
import pandas as pd

In [23]:
df = pd.read_csv("/content/Heat Stroke (1).csv")
df

,Daily Ingested Water (L),Time of year (month),Cardiovascular disease history,Dehydration,Heat Index (HI),Diastolic BP,Environmental temperature (C),Sickle Cell Trait (SCT),Systolic BP,Weight (kg),...,Heart / Pulse rate (b/min),Age,Sweating,"Skin color (flushed/normal=1, pale=0.5, cyatonic=0)",Strenuous exercise,Nationality,Sex,Hot/dry skin,Time of day,Heat stroke
0,2.821588,7.000000,0,0,107.296910,20.000000,39.000000,0,60.000000,48.364079,...,166.000000,38.000000,0,0.021014,0.500000,1,1,0,10.550628,1
1,5.000000,6.841842,0,0,105.410610,90.000000,37.700000,0,120.000000,52.413863,...,68.000000,50.000000,1,0.045987,0.000000,1,0,0,10.613669,1
2,5.000000,4.636197,0,0,101.823065,50.000000,37.700000,0,100.000000,46.344503,...,96.000000,64.000000,0,0.031299,0.000000,1,0,0,14.419615,1
3,10.500000,2.589828,0,0,95.925389,78.000000,37.700000,0,116.000000,42.132476,...,70.000000,19.000000,0,0.052654,0.000000,1,0,0,9.467515,1
4,5.000000,9.914389,0,0,101.673016,88.000000,37.700000,0,130.000000,41.856694,...,88.000000,21.000000,1,0.076099,0.000000,1,0,0,12.460315,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,2.625332,11.808261,0,0,69.444843,82.705255,28.276056,0,117.025213,45.173841,...,106.868166,28.952569,1,0.060595,0.038827,1,1,0,16.994422,0
605,1.069333,7.369952,0,0,67.273039,83.822981,26.008688,0,116.654793,53.125129,...,93.713145,52.733157,1,0.031162,0.657076,0,1,0,12.034963,0
606,1.085594,6.955786,0,0,53.017902,85.101995,32.863125,0,112.713272,47.898687,...,143.858902,21.496651,0,0.015298,0.260901,0,0,0,16.545827,0
607,5.916055,2.741906,0,0,78.665639,88.765944,22.353665,0,111.962413,52.487889,...,181.952819,26.420689,0,0.050419,0.305553,1,0,0,16.757862,0
608,5.654623,2.287122,0,0,77.649841,84.971577,33.082008,0,110.941965,51.229314,...,136.743099,19.029703,0,0.041355,0.808819,0,0,0,14.171093,0

In [3]:
df.shape

(609, 27)

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR

In [8]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
rf = RandomForestRegressor()
svr = SVR()

In [9]:
estimators = [('lr',lr),('dt',dt),('rf',rf),('svr',svr)]

In [17]:
X = df.drop('Heat stroke', axis=1)
y = df['Heat stroke']

In [18]:

for estimator in estimators:
    scores = cross_val_score(estimator[1], X, y, cv=10)
    print(estimator[0], np.round(np.mean(scores), 2))

lr 0.06
dt 0.9
rf 0.8
svr 0.01

In [19]:
from sklearn.ensemble import VotingRegressor
vr = VotingRegressor(estimators)
scores = cross_val_score(vr, X, y,scoring = 'r2', cv=10)
print("Voting Regressor", np.round(np.mean(scores), 2))

Voting Regressor 0.09

In [22]:
for i in range(1, 4):
  for j in range(1, 4):
    for k in range(1, 4):
      for m in range(1, 4):
        vr = VotingRegressor(estimators, weights=[i, j, k, m])
        scores = cross_val_score(vr, X, y, scoring='r2', cv=10)
        print("For i = {}, j = {}, k = {}, m = {}".format(i, j, k, m), np.round(np.mean(scores), 2))

For i = 1, j = 1, k = 1, m = 1 0.09
For i = 1, j = 1, k = 1, m = 2 0.08
For i = 1, j = 1, k = 1, m = 3 0.08
For i = 1, j = 1, k = 2, m = 1 0.09
For i = 1, j = 1, k = 2, m = 2 0.09
For i = 1, j = 1, k = 2, m = 3 0.08
For i = 1, j = 1, k = 3, m = 1 0.1
For i = 1, j = 1, k = 3, m = 2 0.09
For i = 1, j = 1, k = 3, m = 3 0.09
For i = 1, j = 2, k = 1, m = 1 0.09
For i = 1, j = 2, k = 1, m = 2 0.09
For i = 1, j = 2, k = 1, m = 3 0.08
For i = 1, j = 2, k = 2, m = 1 0.1
For i = 1, j = 2, k = 2, m = 2 0.09
For i = 1, j = 2, k = 2, m = 3 0.09
For i = 1, j = 2, k = 3, m = 1 0.1
For i = 1, j = 2, k = 3, m = 2 0.09
For i = 1, j = 2, k = 3, m = 3 0.09
For i = 1, j = 3, k = 1, m = 1 0.1
For i = 1, j = 3, k = 1, m = 2 0.09
For i = 1, j = 3, k = 1, m = 3 0.09
For i = 1, j = 3, k = 2, m = 1 0.1
For i = 1, j = 3, k = 2, m = 2 0.09
For i = 1, j = 3, k = 2, m = 3 0.09
For i = 1, j = 3, k = 3, m = 1 0.1
For i = 1, j = 3, k = 3, m = 2 0.1
For i = 1, j = 3, k = 3, m = 3 0.09
For i = 2, j = 1, k = 1, m = 1 0.09
For i = 2, j = 1, k = 1, m = 2 0.09
For i = 2, j = 1, k = 1, m = 3 0.08
For i = 2, j = 1, k = 2, m = 1 0.09
For i = 2, j = 1, k = 2, m = 2 0.09
For i = 2, j = 1, k = 2, m = 3 0.09
For i = 2, j = 1, k = 3, m = 1 0.09
For i = 2, j = 1, k = 3, m = 2 0.09
For i = 2, j = 1, k = 3, m = 3 0.09
For i = 2, j = 2, k = 1, m = 1 0.09
For i = 2, j = 2, k = 1, m = 2 0.09
For i = 2, j = 2, k = 1, m = 3 0.09
For i = 2, j = 2, k = 2, m = 1 0.09
For i = 2, j = 2, k = 2, m = 2 0.09
For i = 2, j = 2, k = 2, m = 3 0.09
For i = 2, j = 2, k = 3, m = 1 0.1
For i = 2, j = 2, k = 3, m = 2 0.09
For i = 2, j = 2, k = 3, m = 3 0.09
For i = 2, j = 3, k = 1, m = 1 0.09
For i = 2, j = 3, k = 1, m = 2 0.09
For i = 2, j = 3, k = 1, m = 3 0.09
For i = 2, j = 3, k = 2, m = 1 0.1
For i = 2, j = 3, k = 2, m = 2 0.09
For i = 2, j = 3, k = 2, m = 3 0.09
For i = 2, j = 3, k = 3, m = 1 0.1
For i = 2, j = 3, k = 3, m = 2 0.09
For i = 2, j = 3, k = 3, m = 3 0.09
For i = 3, j = 1, k = 1, m = 1 0.09
For i = 3, j = 1, k = 1, m = 2 0.09
For i = 3, j = 1, k = 1, m = 3 0.08
For i = 3, j = 1, k = 2, m = 1 0.09
For i = 3, j = 1, k = 2, m = 2 0.09
For i = 3, j = 1, k = 2, m = 3 0.09
For i = 3, j = 1, k = 3, m = 1 0.09
For i = 3, j = 1, k = 3, m = 2 0.09
For i = 3, j = 1, k = 3, m = 3 0.09
For i = 3, j = 2, k = 1, m = 1 0.09
For i = 3, j = 2, k = 1, m = 2 0.09
For i = 3, j = 2, k = 1, m = 3 0.09
For i = 3, j = 2, k = 2, m = 1 0.09
For i = 3, j = 2, k = 2, m = 2 0.09
For i = 3, j = 2, k = 2, m = 3 0.09
For i = 3, j = 2, k = 3, m = 1 0.09
For i = 3, j = 2, k = 3, m = 2 0.09
For i = 3, j = 2, k = 3, m = 3 0.09
For i = 3, j = 3, k = 1, m = 1 0.09
For i = 3, j = 3, k = 1, m = 2 0.09
For i = 3, j = 3, k = 1, m = 3 0.09
For i = 3, j = 3, k = 2, m = 1 0.09
For i = 3, j = 3, k = 2, m = 2 0.09
For i = 3, j = 3, k = 2, m = 3 0.09
For i = 3, j = 3, k = 3, m = 1 0.1
For i = 3, j = 3, k = 3, m = 2 0.09
For i = 3, j = 3, k = 3, m = 3 0.09

# **Using Same Algorithm**

In [24]:
dt1 = DecisionTreeRegressor(max_depth=1)
dt2 = DecisionTreeRegressor(max_depth=3)
dt3 = DecisionTreeRegressor(max_depth=5)
dt4 = DecisionTreeRegressor(max_depth=7)
dt5 = DecisionTreeRegressor(max_depth=None)

estimators = [('dt1',dt1),('dt2',dt2),('dt3',dt3),('dt4',dt4),('dt5',dt5)]

for estimator in estimators:
    scores = cross_val_score(estimator[1], X, y, cv=10)
    print(estimator[0], np.round(np.mean(scores), 2))

dt1 0.9
dt2 0.9
dt3 0.9
dt4 0.9
dt5 0.9

In [25]:

vr = VotingRegressor(estimators)
scores = cross_val_score(vr, X, y,scoring = 'r2', cv=10)
print("Voting Regressor", np.round(np.mean(scores), 2))

Voting Regressor 0.9